name: 'CircleCI Pipeline Polling'
description: 'Wait for all CircleCI tasks to complete'
inputs:
  interval:
    description: Rate at which to poll the pipeline (in seconds)
    default: 10
  pipeline:
    description: CircleCI Pipeline ID
    required: true
  timeout:
    description: How long to wait for all workflows to complete (in minutes)
    default: 15
  token:
    description: CircleCI Auth Token
    required: true
runs:
  using: 'node16'
  main: 'index.js'
